name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'firebase-hosting/**'
      - '.github/workflows/deploy-firebase-hosting.yml'

env:
  PROJECT_ID: granblue-247222
  CI_SERVICE_ACCOUNT: github-deployer@granblue-247222.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/964139672422/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: '${{ env.CI_SERVICE_ACCOUNT }}'

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        channelId: live
        projectId: ${{ env.PROJECT_ID }}
        entryPoint: ./firebase-hosting
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

