name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'firebase-hosting/**'
      - '.github/workflows/deploy-firebase-hosting.yml'

env:
  PROJECT_ID: granblue-247222

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: ${{ env.PROJECT_ID }}
        entryPoint: ./firebase-hosting

