name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - 'firebase-hosting/**'
      - '.github/workflows/deploy-firebase-hosting.yml'

# This workflow requires the service account to have the following roles:
# - Service Account Key Admin (roles/iam.serviceAccountKeyAdmin)
# - Firebase Hosting Admin (roles/firebasehosting.admin)

env:
  PROJECT_ID: granblue-247222
  CI_SERVICE_ACCOUNT: github-deployer@granblue-247222.iam.gserviceaccount.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/964139672422/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: '${{ env.CI_SERVICE_ACCOUNT }}'

    - name: Create service account key
      id: create_key
      run: |
        gcloud iam service-accounts keys create key.json --iam-account=${{ env.CI_SERVICE_ACCOUNT }}
        echo "key_id=$(jq -r .private_key_id key.json)" >> $GITHUB_OUTPUT
        echo "key_json=$(cat key.json)" >> $GITHUB_OUTPUT

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ steps.create_key.outputs.key_json }}'
        channelId: live
        projectId: ${{ env.PROJECT_ID }}
        entryPoint: ./firebase-hosting

    - name: Revoke service account key
      if: always()
      run: |
        gcloud iam service-accounts keys delete ${{ steps.create_key.outputs.key_id }} --iam-account=${{ env.CI_SERVICE_ACCOUNT }} -q


