name: Deploy Cloud Run Job

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: granblue-247222
  REGION: asia-northeast1
  SERVICE_ACCOUNT: github-deployer@granblue-247222.iam.gserviceaccount.com
  IMAGE_NAME: hello-job
  REPO_NAME: my-docker-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/964139672422/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: '${{ env.SERVICE_ACCOUNT }}'

    - name: Build and Push Image
      run: |-
        gcloud builds submit --pack image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} --project=${{ env.PROJECT_ID }} cloud-run_helloworld

    - name: Deploy Job
      run: |-
        gcloud run jobs replace ${{ env.IMAGE_NAME }} \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }} \
          --region ${{ env.REGION }} \
          --service-account ${{ env.SERVICE_ACCOUNT }} \
          --project ${{ env.PROJECT_ID }}
